[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.3"

[[override]]
  name = "github.com/spf13/pflag"
  version = "v1.0.2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.1"

[[constraint]]
  name = "github.com/cloudevents/sdk-go"
  revision = "17c1655cb929797454995e53fd412c8ac55a7475"

[[constraint]]
  name = "github.com/google/go-github"
  version = "v18.0.0"

